#!/usr/bin/env bash
#

# Ask for admin password upfront
sudo -v
# Keep-alive: update existing sudo timestamp until the script has finished.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2> /dev/null &

# install & update Homebrew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew update
brew upgrade --all

# Install GNU core utilities (OS X ones are outdated)
# (remember to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
brew install coreutils
sudo ln -s /usr/local/bin/gsha256sum /usr/local/bin/sha256sum

brew install moreutils
brew install findutils
brew install gnu-sed --with-default-names  		#Install GNU sed and overwrite built-in

# install Bash 4 (this is for security, I use zsh)
brew install bash

# Install more recent versions of some OS X tools
brew install vim --override-system-vi
brew install homebrew/dupes/grep
brew install homebrew/dupes/openssh

# install other binaries
binaries=(
  graphicsmagick
  webkit2png
  rename
  zopfli
  ffmpeg
  python
  trash
  tree
  ack
  wget
  hub
  git
  postgresql
  zsh
  zsh-completions
  tmux
  heroku-toolbelt
  dark-mode
)

echo "installing other binaries..."
brew install ${binaries[@]}

echo "installing rvm..."
\curl -sSL https://get.rvm.io | bash -s stable

apps=(
  # core
  alfred
  mactracker
  dropbox
  iterm2
  google-chrome
  firefox
  slack
  vlc
  flux
  skype
  transmission
  appcleaner
  spectacle

  # development
  sourcetree
  sublime-text3
  macvim
  lighttable
  virtualbox
  vagrant
  node

  # quicklook
  qlstephen
  qlprettypatch
  qlcolorcode
  qlmarkdown
  quicklook-json

  # google
  google-drive
  google-earth
)

# install apps to /Applications rather than /Users/$user/Applications
echo "installing applications..."
brew install caskroom/cask/brew-cask
brew tap caskroom/versions
brew cask install --appdir="/Applications" ${apps[@]}

fonts=(
  source-code-pro
)

echo "installing some fonts..."
brew tap caskroom/fonts
brew cask install font-${fonts[@]}

brew cleanup --force
rm -rf /Library/Caches/Homebrew/*

# install oh-my-zsh
curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# download Solarized Dark for iTerm2
wget https://raw.githubusercontent.com/altercation/solarized/master/iterm2-colors-solarized/Solarized%20Dark.itermcolors -O ~/Downloads/
