#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# install "general" packages
while read p; do
  echo "installing $p..."
  apt-get install -y $p 
done < packages

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do sh -c "${installer}" ; done

# fix my ownership because script was run as root
# (this is dumb and there's probably a better way
chown -R james:james /home/james/*
